pipeline:
  install:
    image: node:8
    commands:
      - git config --global user.email "you@example.com"
      - git config --global user.name "Your Name"
      - npm install
      - node main.js
